apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: employees-frontend
    stack: echo
    interface: rest
    language: reactjs
  name: employees-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: employees-frontend
  type: LoadBalancer # LoadBalancer
