apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: employees-backend
    stack: echo
    interface: rest
    language: csharp
  name: employees-backend
spec:
  ports:
    - name: http
      port: 80 # 8080 
      protocol: TCP
      targetPort: 80
  selector:
    app: employees-backend
  type: LoadBalancer # LoadBalancer
