apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: employees-frontend
  name: employees-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: employees-frontend
  template:
    metadata:
      labels:
        app: employees-frontend
        version: v1
        stack: echo
        interface: rest
        language: reactjs
    spec:
      containers:
        - image: richiebono/employees-frontend:latest
          name: employees-frontend
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "5Mi"
              cpu: "100m"
            limits:
              memory: "10Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10        
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
