apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: employees-frontend
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: employees-frontend
              port:
                number: 80